from typing import Optional, List
from pydantic import BaseModel, Field


class RoadmapGenerationRequest(BaseModel):
    """User request for AI-assisted roadmap generation."""
    user_id: int = Field(..., ge=1, description="ID of the user requesting the roadmap")
    goal: str = Field(..., min_length=3, max_length=500, description="The learning or execution goal")
    target_duration_days: int = Field(..., ge=1, le=365, description="Target total duration in days")
    daily_available_minutes: Optional[int] = Field(
        None,
        ge=1,
        le=1440,
        description="Optional daily available study/work time in minutes",
    )
    context: Optional[str] = Field(
        None,
        max_length=2000,
        description="Optional user context, current skill level, or preferences",
    )


class GeneratedTask(BaseModel):
    """Structured task generated by the AI."""
    title: str = Field(..., min_length=1, max_length=255, description="Task title")
    description: Optional[str] = Field(None, max_length=2000, description="Task details or instructions")
    estimated_minutes: int = Field(..., ge=1, le=1440, description="Estimated duration in minutes")
    category: Optional[str] = Field(None, max_length=100, description="Task category or subject area")
    order_index: int = Field(..., ge=0, description="Sequential order within the day (0-indexed)")


class GeneratedDay(BaseModel):
    """Structured day container generated by the AI."""
    day_number: int = Field(..., ge=1, description="1-based day number in the roadmap")
    title: Optional[str] = Field(None, max_length=255, description="Day topic or milestone title")
    tasks: List[GeneratedTask] = Field(
        ...,
        min_length=1,
        description="List of tasks for this day. Must contain at least one task.",
    )


class GeneratedRoadmap(BaseModel):
    """Complete structured roadmap output generated by the AI."""
    title: str = Field(..., min_length=1, max_length=255, description="Roadmap title")
    description: Optional[str] = Field(None, max_length=2000, description="Roadmap summary")
    target_duration_days: int = Field(..., ge=1, description="Target total duration in days")
    days: List[GeneratedDay] = Field(
        ...,
        min_length=1,
        description="List of days matching the requested duration",
    )
