import re
from typing import Optional, List
from pydantic import BaseModel, Field, field_validator

# ---------------------------------------------------------------------------
# Title normalization
# ---------------------------------------------------------------------------
_TITLE_MAX_LEN = 255


def normalize_ai_title(raw: str, max_length: int = _TITLE_MAX_LEN) -> str:
    """Deterministically normalize an AI-produced title to fit within *max_length*.

    Steps (all deterministic, no AI involvement):
    1. Collapse all whitespace sequences (including newlines/tabs) to a single space.
    2. Strip leading/trailing whitespace.
    3. If the result fits within max_length, return it unchanged.
    4. Otherwise truncate at the last word boundary (space) before max_length,
       appending "…" (U+2026) so the intent is preserved.
    5. As a final safety net, hard-truncate to max_length if step 4 still
       somehow exceeds it (e.g. a single token longer than max_length).
    6. If the result would be empty, return a safe placeholder.

    The schema max_length constraint remains 255 — this function guarantees
    that any raw string passed to it will satisfy that constraint.
    """
    if not isinstance(raw, str):
        raw = str(raw)

    # Step 1 & 2: normalise whitespace
    normalised = re.sub(r"\s+", " ", raw).strip()

    if not normalised:
        return "Untitled Roadmap"

    if len(normalised) <= max_length:
        return normalised

    # Step 4: truncate at word boundary leaving room for ellipsis
    ellipsis = "…"  # single character (U+2026)
    target = max_length - len(ellipsis)  # 254 when max_length=255
    cut = normalised.rfind(" ", 0, target)
    if cut > 0:
        truncated = normalised[:cut].rstrip() + ellipsis
    else:
        # Single enormous token — hard cut
        truncated = normalised[:target] + ellipsis

    # Step 5: absolute safety net (should never trigger, but be defensive)
    return truncated[:max_length]


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

class RoadmapGenerationRequest(BaseModel):
    """User request for AI-assisted roadmap generation."""
    user_id: int = Field(..., ge=1, description="ID of the user requesting the roadmap")
    goal: str = Field(..., min_length=3, max_length=500, description="The learning or execution goal")
    target_duration_days: int = Field(..., ge=1, le=365, description="Target total duration in days")
    daily_available_minutes: Optional[int] = Field(
        None,
        ge=1,
        le=1440,
        description="Optional daily available study/work time in minutes",
    )
    context: Optional[str] = Field(
        None,
        max_length=2000,
        description="Optional user context, current skill level, or preferences",
    )


class GeneratedTask(BaseModel):
    """Structured task generated by the AI."""
    title: str = Field(..., min_length=1, max_length=255, description="Task title")
    description: Optional[str] = Field(None, max_length=2000, description="Task details or instructions")
    estimated_minutes: int = Field(..., ge=1, le=1440, description="Estimated duration in minutes")
    category: Optional[str] = Field(None, max_length=100, description="Task category or subject area")
    order_index: int = Field(..., ge=0, description="Sequential order within the day (0-indexed)")

    @field_validator("title", mode="before")
    @classmethod
    def normalize_title(cls, v: str) -> str:
        """Normalize task title before length validation fires."""
        return normalize_ai_title(v, max_length=255)


class GeneratedDay(BaseModel):
    """Structured day container generated by the AI."""
    day_number: int = Field(..., ge=1, description="1-based day number in the roadmap")
    title: Optional[str] = Field(None, max_length=255, description="Day topic or milestone title")
    tasks: List[GeneratedTask] = Field(
        ...,
        min_length=1,
        description="List of tasks for this day. Must contain at least one task.",
    )


class GeneratedRoadmap(BaseModel):
    """Complete structured roadmap output generated by the AI."""
    title: str = Field(..., min_length=1, max_length=255, description="Roadmap title")
    description: Optional[str] = Field(None, max_length=2000, description="Roadmap summary")
    target_duration_days: int = Field(..., ge=1, description="Target total duration in days")
    days: List[GeneratedDay] = Field(
        ...,
        min_length=1,
        description="List of days matching the requested duration",
    )

    @field_validator("title", mode="before")
    @classmethod
    def normalize_title(cls, v: str) -> str:
        """Normalize roadmap title before length validation fires.

        This is the primary normalization boundary for all AI provider output.
        It runs before Pydantic's max_length check, so an oversized AI title
        is safely truncated rather than causing a ValidationError.
        """
        return normalize_ai_title(v, max_length=255)
