"""add_notifications_and_preferences

Revision ID: edb8d80c45dc
Revises: 7c33b8d5d8d1
Create Date: 2026-09-23 16:22:36.112743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb8d80c45dc'
down_revision: Union[str, Sequence[str], None] = '7c33b8d5d8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('DAILY_FOCUS', 'DAY_INCOMPLETE', 'OVER_CAPACITY', 'ROADMAP_COMPLETE', 'REMINDER', name='notificationtype', native_enum=False, length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'ATTENTION', 'SUCCESS', name='notificationseverity', native_enum=False, length=20), nullable=False),
    sa.Column('action', sa.Enum('VIEW_TODAY', 'VIEW_ROADMAP', 'VIEW_SETTINGS', name='notificationaction', native_enum=False, length=30), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_dedup_key'), 'notifications', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.add_column('users', sa.Column('daily_reminder_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.add_column('users', sa.Column('daily_reminder_time', sa.String(length=5), server_default='19:00', nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'daily_reminder_time')
    op.drop_column('users', 'daily_reminder_enabled')
    op.drop_column('users', 'notifications_enabled')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedup_key'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
