"""add_theme_and_roadmap_preferences_to_user

Revision ID: f89d1f23c55d
Revises: edb8d80c45dc
Create Date: 2026-09-23 16:55:56.141013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89d1f23c55d'
down_revision: Union[str, Sequence[str], None] = 'edb8d80c45dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.String(length=20), server_default='system', nullable=False))
    op.add_column('users', sa.Column('ask_before_reschedule', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ask_before_reschedule')
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
